import Card from "./card"
export default function Feed() {
    return(
        <main className="flex flex-col gap-8 row-start-2 items-center px-5">
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
            <Card>hello</Card>
        </main>
    );
}
