export default function Feed() {
    return(
        <main className="flex flex-col gap-8 row-start-2 items-center">
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
            <div className="px-4">hello</div>
        </main>
    );
}
